(() => {
  'use strict';
  const config = window.CUBE_CLUB_CONFIG || {};
  const API = (config.CUBE_CLUB_API_URL || '').replace(/\/$/, '');
  const isLocal = ['localhost','127.0.0.1'].includes(location.hostname);
  const demoEnabled = Boolean(config.DEMO_MODE && isLocal);
  const demo = {
    me:{id:'demo-1',username:'CubeNinja',display_name:'CubeNinja',points:4250,rank:7,best_single:24.83,best_average:29.72,total_solves:1284,completed_goals:8,achievements_count:17,token_expires_at:'2026-10-11T00:00:00Z',title:'Rising Solver'},
    transactions:[{description:'Completed 50 solves',amount:100,date:'Today'},{description:'Reached Sub-30',amount:250,date:'Yesterday'},{description:'Club weekly challenge',amount:75,date:'Sep 30'}],
    goals:[{name:'50 Solves',reward:100,state:'COMPLETED',progress:50,target:50},{name:'100 Solves',reward:250,state:'COMPLETED',progress:100,target:100},{name:'Sub-45 Single',reward:500,state:'IN PROGRESS',progress:24.83,target:45,inverse:true},{name:'Sub-30 Single',reward:1000,state:'COMPLETED',progress:24.83,target:30,inverse:true},{name:'Sub-20 Single',reward:2500,state:'LOCKED',progress:24.83,target:20,inverse:true}],
    leaderboard:[{display_name:'CubeNinja',value:'12,450 CP'},{display_name:'SpeedCubingPro',value:'11,820 CP'},{display_name:'TwistMaster',value:'9,750 CP'},{display_name:'CrossAndGo',value:'8,420 CP'},{display_name:'CubeNinja',value:'4,250 CP'}],
    shop:[{id:'candy',name:'Candy',category:'CANDY',price:100,emoji:'🍬',description:'A sweet club treat.'},{id:'small-reward',name:'Small Digital Reward',category:'DIGITAL REWARDS',price:500,emoji:'🎟️',description:'A little digital surprise.'},{id:'steam',name:'Steam Gift Card',category:'DIGITAL REWARDS',price:2500,emoji:'🎮',description:'Fulfilled by a club administrator.'},{id:'apple',name:'Apple Gift Card',category:'DIGITAL REWARDS',price:5000,emoji:'🍎',description:'Fulfilled by a club administrator.'},{id:'club-reward',name:'Special Club Reward',category:'CLUB PERKS',price:7500,emoji:'🏆',description:'A special perk for dedicated members.'},{id:'honor',name:'Honor Treatment',category:'SPECIAL REWARDS',price:10000,emoji:'👑',description:'Reach 10,000 Cube Points and earn the ultimate Cube Club honor.',legendary:true}],
    redemptions:[]
  };
  const samples = demoEnabled ? demo : {me:{},transactions:[],goals:[],leaderboard:[],shop:[],redemptions:[]};
  let me = null, cache = {}, toast = '';
  const routeNames = ['home','dashboard','goals','leaderboard','shop','rewards','profile','admin'];
  const navItems = [['home','⌂','HOME'],['dashboard','▦','DASHBOARD'],['goals','◎','GOALS'],['leaderboard','♜','LEADERBOARD'],['shop','✦','SHOP'],['rewards','▤','REWARDS'],['profile','◉','PROFILE'],['admin','⚙','ADMIN']];
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt = n => Number(n || 0).toLocaleString();
  const date = value => value ? new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}) : '—';
  const path = () => (location.hash.replace(/^#\/?/,'').split('/')[0] || 'home');
  const navigate = p => { location.hash = '#/'+p; };
  async function request(endpoint, options={}) {
    if (demoEnabled && !API) return demoRequest(endpoint, options);
    if (!API) throw new Error('The Cube Club API is not configured yet. Add CUBE_CLUB_API_URL in config.js.');
    const headers = {'Content-Type':'application/json', ...(options.headers||{})};
    if (me?.session_token) headers.Authorization = `Bearer ${me.session_token}`;
    let response;
    try { response = await fetch(API+endpoint,{...options,headers,credentials:'include'}); }
    catch { throw new Error('Could not reach the club API. Check the API URL and CORS settings.'); }
    const body = await response.json().catch(()=>({}));
    if (!response.ok) {
      const messages = {TOKEN_EXPIRED:'TOKEN EXPIRED — return to your Account Hub and generate a new token.',TOKEN_REVOKED:'TOKEN REVOKED — return to your Account Hub for help.',INVALID_TOKEN:'INVALID TOKEN'};
      throw new Error(messages[body.code] || body.message || `Request failed (${response.status}).`);
    }
    return body;
  }
  async function demoRequest(endpoint, options) {
    if (endpoint==='/auth/token') { if (!options.body || !JSON.parse(options.body).token) throw new Error('Enter your Cube Club token.'); return {user:demo.me,session_token:'DEMO_SESSION_ONLY'}; }
    if (endpoint==='/auth/logout') return {};
    if (endpoint==='/me') return {user:demo.me};
    if (endpoint==='/me/stats') return {stats:demo.me};
    if (endpoint==='/me/transactions') return {transactions:demo.transactions};
    if (endpoint==='/me/goals') return {goals:demo.goals};
    if (endpoint.startsWith('/leaderboard')) return {entries:demo.leaderboard};
    if (endpoint==='/shop') return {items:demo.shop};
    if (endpoint==='/redemptions' && options.method==='POST') {let b=JSON.parse(options.body);let item=demo.shop.find(x=>x.id===b.shop_item_id);if(!item)throw new Error('Reward not found.');if(item.price>demo.me.points)throw new Error('You do not have enough Cube Points.');demo.me.points-=item.price;demo.redemptions.unshift({reward:item.name,cost:item.price,status:'PENDING',created_at:new Date().toISOString()});return {redemption:demo.redemptions[0]};}
    if (endpoint==='/redemptions') return {redemptions:demo.redemptions};
    if (endpoint==='/me/profile') return {profile:demo.me};
    if (endpoint==='/admin/overview') throw new Error('Administrator access is unavailable in demo mode.');
    return {};
  }
  async function loadData(route) {
    if (!me) return;
    const profileId = decodeURIComponent(location.hash.split('/')[2] || '');
    const jobs = {dashboard:['/me','/me/stats','/me/transactions','/me/goals'],goals:['/me/goals'],leaderboard:['/leaderboard?category=cube_points&period=all_time'],shop:['/shop'],rewards:['/redemptions'],profile:[profileId?`/profiles/${encodeURIComponent(profileId)}`:'/me/profile'],admin:['/admin/overview']};
    for (const url of (jobs[route]||[])) { try { cache[url.split('?')[0]]=await request(url); } catch(e) { cache[url.split('?')[0]]={error:e.message}; } }
  }
  function statusNotice(){ return toast ? `<div class="notice ${toast.startsWith('Error:')?'error':'success'}">${esc(toast.replace(/^Error: ?/,''))}</div>` : ''; }
  function brand(){ return `<div class="brand"><div class="cube-mark">✦</div><div>CUBE CLUB<small>SPEEDCUBING COMMUNITY</small></div></div>`; }
  function login(){
    const hub=config.ACCOUNT_HUB_URL||'#';
    return `<div class="login-wrap"><section class="form-card">${brand()}<h1>🧊 CUBE CLUB</h1><p class="sub">Welcome to the speedcubing club.</p>${statusNotice()}<form id="login-form"><div class="field"><label for="token">Enter your Cube Club Token</label><input id="token" name="token" type="password" autocomplete="off" placeholder="CC-••••-••••-••••" required></div><button class="btn" type="submit">ENTER CLUB <span>↗</span></button></form><div class="login-links"><a href="${esc(hub)}">Create an Account</a><a href="${esc(hub)}">Get a Token</a><a href="#how">How It Works</a></div><div id="how" class="notice">Your token only proves who you are. Your Cube Points, solves, and profile come from the secure club backend.</div>${demoEnabled?'<div class="notice success">Local demo mode is on. Use any non-empty token. Demo rewards have no real value.</div>':''}<div class="footer">Cube Club • Solve together, get better together</div></section></div>`;
  }
  function nav(route){return `<nav class="nav">${navItems.filter(x=>x[0]!=='admin'||me?.is_admin).map(([id,icon,label])=>`<a href="#/${id}" class="${route===id?'active':''}">${icon} &nbsp;${label}</a>`).join('')}</nav>`;}
  function shell(route,content){return `<div class="shell"><aside class="sidebar">${brand()}${nav(route)}<div class="side-bottom"><div class="side-card"><span class="eyebrow">YOUR CLUB STATUS</span><p>Token session verified securely.</p><div class="status-line"><i class="dot"></i> ${demoEnabled?'DEVELOPMENT DEMO':'CONNECTED'}</div></div><button class="quiet-btn" data-action="logout">↪ &nbsp; Sign out</button></div></aside><main class="main"><header class="topbar"><div class="crumb">CUBE CLUB <span style="color:var(--line)">/</span> ${esc(route)}</div><div class="tools"><button class="icon-btn" data-action="theme" aria-label="Toggle theme">◐</button><span class="user-label">${esc(me?.display_name||me?.username||'Member')}</span><div class="avatar">${esc((me?.display_name||'M')[0].toUpperCase())}</div></div></header>${content}<div class="footer">Cube Club · Keep it fair, keep it fun. &nbsp; <a href="${esc(config.ACCOUNT_HUB_URL||'#')}" class="text-link">Account Hub ↗</a></div></main><nav class="mobile-nav">${navItems.filter(x=>x[0]!=='admin'||me?.is_admin).map(([id,icon,label])=>`<a href="#/${id}" class="${route===id?'active':''}"><span>${icon}</span>${label}</a>`).join('')}</nav></div>`;}
  function stat(label,value,icon,foot='From your verified club account'){return `<article class="card"><div class="stat-label">${label}<span class="stat-icon">${icon}</span></div><div class="stat-value">${value}</div><div class="stat-foot">${foot}</div></article>`;}
  function transactionRows(items){return (items||[]).length?(items||[]).slice(0,5).map(t=>`<div class="activity"><div class="activity-icon">${Number(t.amount)>=0?'✦':'↘'}</div><div class="activity-copy"><b>${esc(t.description||t.reason||'Points activity')}</b><small>${date(t.created_at||t.date)}</small></div><span class="amount">${Number(t.amount)>=0?'+':''}${fmt(t.amount)} CP</span></div>`).join(''):'<div class="empty">Your points activity will appear here.</div>';}
  function goalRows(items, compact=false){return (items||[]).slice(0,compact?3:100).map(g=>{let pct=Math.min(100,g.progress_percent??(g.inverse?100-(Number(g.progress||0)/Number(g.target||1))*100:(Number(g.progress||0)/Number(g.target||1))*100)); if(g.state==='COMPLETED')pct=100;return `<div class="goal-row"><div class="goal-symbol">${g.name?.toLowerCase().includes('solve')?'🎯':'⚡'}</div><div class="goal-meta"><b>${esc(g.name)}</b><p>Reward: ${fmt(g.reward_points??g.reward)} CP ${g.state==='IN PROGRESS'?`· ${Math.round(pct)}%`:''}</p>${g.state==='IN PROGRESS'?`<div class="progress"><i style="width:${pct}%"></i></div>`:''}</div><span class="badge ${g.state==='COMPLETED'?'done':g.state==='LOCKED'?'locked':''}">${esc(g.state||'IN PROGRESS')}</span></div>`}).join('')||'<div class="empty">Goals configured by the club will show here.</div>';}
  function dashboard(){const u=cache['/me']?.user||me||{},st=cache['/me/stats']?.stats||u,tx=cache['/me/transactions']?.transactions||samples.transactions,goals=cache['/me/goals']?.goals||samples.goals;const apiErr=cache['/me']?.error?`<div class="notice error">${esc(cache['/me'].error)}</div>`:'';return `${apiErr}<section class="hero"><div class="hero-inner"><span class="eyebrow">YOUR NEXT PERSONAL BEST STARTS HERE</span><h1>Welcome, ${esc(u.display_name||u.username||'Solver')}! 👋</h1><p>Every solve moves your story forward. Check your progress, chase the next goal, and take your place on the board.</p><a class="btn" href="#/goals">Explore your goals <span>→</span></a></div></section><div class="grid stats">${stat('CUBE POINTS',`${fmt(st.points??st.cube_points)} <small style="font-size:13px">CP</small>`,'🧊','Earned through verified club activity')}${stat('CLUB RANK',`#${fmt(st.rank)}`,'🏆','Your current all-time standing')}${stat('BEST SINGLE',`${st.best_single??'—'}<small style="font-size:13px">s</small>`,'⚡','Verified personal best')}${stat('BEST AVERAGE',`${st.best_average??'—'}<small style="font-size:13px">s</small>`,'📊','Official club average')}${stat('TOTAL SOLVES',fmt(st.total_solves),'🎯','Imported and validated solves')}${stat('COMPLETED GOALS',fmt(st.completed_goals),'◎','Backend-verified milestones')}${stat('ACHIEVEMENTS',fmt(st.achievements_count),'🏅','Badges earned in the club')}${stat('TOKEN STATUS',st.token_expires_at?`<span style="font-size:18px">ACTIVE</span>`:'ACTIVE','🔐',st.token_expires_at?`Expires ${date(st.token_expires_at)}`:'Secure session')}</div><div class="grid columns"><section class="card"><div class="section-head"><h2>Recent points activity</h2><a class="text-link" href="#/rewards">Full history →</a></div><div class="activity-list">${transactionRows(tx)}</div></section><section class="card"><div class="section-head"><h2>Goals in your sights</h2><a class="text-link" href="#/goals">All goals →</a></div><div class="goal-list">${goalRows(goals,true)}</div></section></div>`;}
  function goalsPage(){let d=cache['/me/goals'];return `<h1 class="page-title">Goals & milestones 🎯</h1><p class="sub">Your solve history is checked by the club backend before rewards are issued.</p>${d?.error?`<div class="notice error">${esc(d.error)}</div>`:''}<div class="grid two">${goalRows(d?.goals||samples.goals)}</div><div class="notice">Goal progress is calculated from validated solve records. One-time rewards cannot be claimed repeatedly.</div>`;}
  function leaderboard(){let d=cache['/leaderboard'];let rows=d?.entries||samples.leaderboard;return `<h1 class="page-title">Club leaderboard 🏆</h1><p class="sub">Celebrate great solves, strong streaks, and the community showing up.</p><div class="toolbar"><div class="tabs" id="leader-tabs">${[['cube_points','Cube Points'],['best_single','Best Single'],['best_average','Best Average'],['total_solves','Total Solves'],['weekly_points','Weekly Points'],['monthly_points','Monthly Points']].map(([id,label],i)=>`<button class="tab ${i===0?'active':''}" data-category="${id}">${label}</button>`).join('')}</div><div class="tabs" id="period-tabs"><button class="tab active" data-period="all_time">ALL TIME</button><button class="tab" data-period="this_month">THIS MONTH</button><button class="tab" data-period="this_week">THIS WEEK</button></div></div>${d?.error?`<div class="notice error">${esc(d.error)}</div>`:''}<div class="table-wrap"><table><thead><tr><th>Place</th><th>Member</th><th>Standing</th><th>Club title</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td class="rank">${['🥇','🥈','🥉'][i]||`#${i+1}`}</td><td><a class="member" href="#/profile/${encodeURIComponent(r.id||r.username||r.display_name)}"><span class="mini-avatar">${esc((r.display_name||'?')[0])}</span>${esc(r.display_name||r.username)}</a></td><td><b>${esc(r.value??r.formatted_value??fmt(r.points??r.best_single??r.total_solves))}</b></td><td><span class="badge">${esc(r.title||'Club solver')}</span></td></tr>`).join('')||'<tr><td colspan="4" class="empty">No public leaderboard entries yet.</td></tr>'}</tbody></table></div><p class="muted">Public display names only. Private account details are never listed.</p>`;}
  function shop(){let d=cache['/shop'],items=d?.items||samples.shop;return `<h1 class="page-title">The Cube Shop ✨</h1><p class="sub">Trade your verified Cube Points for club-approved rewards.</p>${d?.error?`<div class="notice error">${esc(d.error)}</div>`:''}<div class="toolbar"><span class="badge">YOUR BALANCE &nbsp; ${fmt(me?.points??samples.me.points)} CP</span><span class="muted">All requests are reviewed and fulfilled by club administrators.</span></div><div class="grid three">${items.map(x=>`<article class="card shop-card ${x.legendary||x.id==='honor'?'legendary':''}"><span class="shop-emoji">${esc(x.emoji||'🎁')}</span><h3>${esc(x.name)}</h3><p>${esc(x.description||'A reward for your hard work.')}</p><div class="shop-footer"><span class="price">${fmt(x.price_points??x.price)} CP</span><button class="btn ${x.legendary||x.id==='honor'?'':'secondary'}" data-redeem="${esc(x.id)}">Request ↗</button></div></article>`).join('')||'<div class="card empty">The club shop is being prepared. Check back soon.</div>'}</div><div class="notice">Gift card rewards create a pending request. Codes are never sent automatically or stored in this site’s frontend.</div>`;}
  function rewards(){let d=cache['/redemptions'],items=d?.redemptions||samples.redemptions;return `<h1 class="page-title">My rewards 🎁</h1><p class="sub">Track your requests from submission through fulfillment.</p>${d?.error?`<div class="notice error">${esc(d.error)}</div>`:''}<div class="table-wrap"><table><thead><tr><th>Reward</th><th>Cost</th><th>Date</th><th>Status</th></tr></thead><tbody>${items.length?items.map(r=>`<tr><td><b>${esc(r.reward_name||r.reward||r.item_name)}</b></td><td>${fmt(r.cost_points??r.cost)} CP</td><td>${date(r.created_at)}</td><td><span class="badge ${r.status==='FULFILLED'?'done':r.status==='PENDING'?'warn':''}">${esc(r.status)}</span></td></tr>`).join(''):'<tr><td colspan="4" class="empty">No reward requests yet. Pick something from the shop when you’re ready.</td></tr>'}</tbody></table></div>`;}
  function profile(){let profileId=decodeURIComponent(location.hash.split('/')[2]||'');let d=cache[profileId?`/profiles/${encodeURIComponent(profileId)}`:'/me/profile'],u=d?.profile||me||{},achievements=d?.achievements||[];return `<h1 class="page-title">${profileId?'Member profile':'Your profile'} ◉</h1><p class="sub">${profileId?'Public statistics shared by this member.':'Choose what the club can show on your public profile.'}</p>${d?.error?`<div class="notice error">${esc(d.error)}</div>`:''}<section class="card profile-head"><div class="avatar profile-avatar">${esc((u.display_name||'C')[0])}</div><div><h2>${esc(u.display_name||u.username||'Club Member')}</h2><p>${esc(u.title||'Cube Club solver')} · Rank #${fmt(u.rank)}</p><span class="badge">MEMBER SINCE ${date(u.created_at)}</span></div></section><div class="grid stats" style="margin-top:16px">${stat('CUBE POINTS',`${fmt(u.points??u.cube_points)} CP`,'🧊')}${stat('BEST SINGLE',`${u.best_single??'—'}s`,'⚡')}${stat('BEST AVERAGE',`${u.best_average??'—'}s`,'📊')}${stat('SOLVES',fmt(u.total_solves),'🎯')}</div>${profileId?'':`<section class="card"><div class="section-head"><h2>Public profile settings</h2><span class="badge">SAVED ON SERVER</span></div><p class="muted">Visibility preferences are controlled by your account backend. Update them in Account Hub.</p><a class="btn secondary" href="${esc(config.ACCOUNT_HUB_URL||'#')}">Manage privacy settings ↗</a></section>`}<section class="card" style="margin-top:16px"><div class="section-head"><h2>Achievements</h2></div><div class="grid three">${achievements.map(a=>`<div class="achievement"><span class="achievement-icon">${esc(a.icon||'🏅')}</span><div><b>${esc(a.name)}</b><small>Earned ${date(a.awarded_at)}</small></div></div>`).join('')||'<div class="empty">Verified achievements will appear here.</div>'}</div></section>`;}
  function admin(){let d=cache['/admin/overview'];return `<h1 class="page-title">Club operations ⚙</h1><p class="sub">Admin actions are permission-checked and recorded by the backend.</p>${d?.error?`<div class="notice error">${esc(d.error)}</div>`:''}<div class="notice">Administrator access comes from your authenticated server session. This page never trusts browser flags such as localStorage.isAdmin.</div><div class="grid admin-grid">${[['Members','👥','Review member accounts and status','/admin/members'],['Solve activity','⏱','Review imported solves and flags','/admin/solves'],['Goals','🎯','Create and edit verified goals','/admin/goals'],['Shop items','🛍️','Manage rewards and prices','/admin/shop-items'],['Redemptions','🎁','Approve, reject, and fulfill requests','/admin/redemptions'],['Audit log','📋','Inspect privileged actions','/admin/audit-logs']].map(([title,icon,desc,url])=>`<article class="card"><span style="font-size:25px">${icon}</span><h3>${title}</h3><p class="muted">${desc}</p><button class="btn secondary" data-admin="${url}">Open queue →</button></article>`).join('')}</div><div class="card" style="margin-top:17px"><h2>Manual points adjustment</h2><p class="muted">Every adjustment requires a reason and is audited with administrator identity and timestamp.</p><button class="btn" data-action="adjust-points">Start adjustment</button></div>`;}
  function home(){return `<h1 class="page-title">Welcome to Cube Club 🧊</h1><p class="sub">Your home for speedcubing, friendly competition, and the next personal best.</p><section class="hero"><div class="hero-inner"><span class="eyebrow">SOLVE · PROGRESS · CELEBRATE</span><h1>One more solve.<br>One step closer.</h1><p>Track verified progress, earn Cube Points for real club milestones, and race your friends up the leaderboard.</p><button class="btn" data-action="go-login">Enter the club →</button></div></section><div class="grid three"><article class="card"><span class="shop-emoji">🎯</span><h3>Goals that count</h3><p class="muted">Milestones checked against your validated solve history.</p></article><article class="card"><span class="shop-emoji">🏆</span><h3>Friendly competition</h3><p class="muted">Compare public stats and find your next rival.</p></article><article class="card"><span class="shop-emoji">🧊</span><h3>Points with purpose</h3><p class="muted">Earn and spend points through secure server-verified activity.</p></article></div>`;}
  function render(){let r=path();if(!routeNames.includes(r))r='profile';if(!me&&r!=='home')return app.innerHTML=login();if(!me&&r==='home')return app.innerHTML=login();let pages={dashboard,goals:goalsPage,leaderboard,shop,rewards,profile,admin,home};app.innerHTML=shell(r,(pages[r]||home)());}
  const app=document.getElementById('app');
  async function goRoute(){let r=path();if(r==='admin'&&!me?.is_admin){navigate('dashboard');return;}if(me)await loadData(r);render();}
  app.addEventListener('submit',async e=>{if(e.target.id!=='login-form')return;e.preventDefault();toast='';const token=new FormData(e.target).get('token');try{let result=await request('/auth/token',{method:'POST',body:JSON.stringify({token})});me={...(result.user||result.account||{}),session_token:result.session_token};if(result.user?.session_token)me.session_token=result.user.session_token;try{const response=await request('/me');me={...me,...(response.user||response.me||{})};}catch{}navigate('dashboard');}catch(err){toast='Error: '+err.message;render();}});
  app.addEventListener('click',async e=>{const link=e.target.closest('a[href^="#/"]');if(link&&link.hash===location.hash){e.preventDefault();goRoute();return;}const btn=e.target.closest('[data-action]');if(btn){let action=btn.dataset.action;if(action==='go-login'){navigate('dashboard');return;}if(action==='theme'){document.body.classList.toggle('light');localStorage.setItem('cube-theme',document.body.classList.contains('light')?'light':'dark');return;}if(action==='logout'){try{await request('/auth/logout',{method:'POST',body:'{}'});}catch{}me=null;cache={};toast='';navigate('home');render();return;}if(action==='adjust-points'){const account_id=prompt('Member account ID (from the admin member record):');if(!account_id)return;const amount=Number(prompt('Adjustment amount in CP (positive or negative):'));if(!Number.isInteger(amount)||amount===0){alert('Enter a non-zero whole number of Cube Points.');return;}const reason=prompt('Required reason for the adjustment:');if(!reason?.trim()){alert('A reason is required.');return;}try{await request('/admin/points-adjustments',{method:'POST',body:JSON.stringify({account_id,amount,reason:reason.trim()})});toast='Points adjustment recorded in the audit log.';await loadData('admin');render();}catch(err){toast='Error: '+err.message;render();}return;}}
    const cat=e.target.closest('[data-category]');if(cat){document.querySelectorAll('[data-category]').forEach(x=>x.classList.remove('active'));cat.classList.add('active');let period=document.querySelector('#period-tabs .active')?.dataset.period||'all_time';try{cache['/leaderboard']=await request(`/leaderboard?category=${cat.dataset.category}&period=${period}`);render();}catch(err){toast='Error: '+err.message;render();}return;}
    const per=e.target.closest('[data-period]');if(per){document.querySelectorAll('[data-period]').forEach(x=>x.classList.remove('active'));per.classList.add('active');let category=document.querySelector('#leader-tabs .active')?.dataset.category||'cube_points';try{cache['/leaderboard']=await request(`/leaderboard?category=${category}&period=${per.dataset.period}`);render();}catch(err){toast='Error: '+err.message;render();}return;}
    const redeem=e.target.closest('[data-redeem]');if(redeem){let id=redeem.dataset.redeem;if(!confirm('Submit a reward request? The backend will verify your balance and deduct points securely.'))return;try{let out=await request('/redemptions',{method:'POST',body:JSON.stringify({shop_item_id:id})});toast=out.demo?'Demo request added.':'Your reward request has been submitted!';await loadData('shop');render();}catch(err){toast='Error: '+err.message;render();}return;}
    const admin=e.target.closest('[data-admin]');if(admin){try{const data=await request(admin.dataset.admin);alert(JSON.stringify(data,null,2));}catch(err){toast='Error: '+err.message;render();}return;}
  });
  app.addEventListener('click',e=>{const help=e.target.closest('a[href="#how"]');if(help){e.preventDefault();document.getElementById('how')?.scrollIntoView({behavior:'smooth'});}});
  window.addEventListener('hashchange',goRoute);
  if(localStorage.getItem('cube-theme')==='light')document.body.classList.add('light');
  // Sessions are restored only by the backend's secure same-site cookie.
  if(API){request('/me').then(r=>{me=r.user||r.me||null;goRoute();}).catch(()=>render());} else render();
})();
